# Generated by Django 5.2.6 on 2025-10-29 22:26

import django.db.models.deletion
import movies.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MovieAdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField()),
                ('end_date', models.DateField()),
                ('showing_times', models.JSONField(blank=True, default=list)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movies/posters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_details', to='movies.movie')),
            ],
            options={
                'unique_together': {('movie', 'admin', 'release_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=255)),
                ('selected_date', models.DateField(default=movies.models.get_tomorrow)),
                ('selected_showtime', models.CharField(max_length=50)),
                ('number_of_seats', models.PositiveIntegerField(default=1)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('movie_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='movies.movieadmindetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reservation_date'],
            },
        ),
    ]
