# Generated by Django 5.2.6 on 2025-10-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('end_date', models.DateField()),
                ('showing_times', models.JSONField(blank=True, default=list)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movies/posters/')),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
