# Generated by Django 5.2.7 on 2025-10-20 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='showing_times',
        ),
        migrations.CreateModel(
            name='MovieAdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField()),
                ('end_date', models.DateField()),
                ('showing_times', models.JSONField(blank=True, default=list)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movies/posters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_details', to='movies.movie')),
            ],
            options={
                'unique_together': {('movie', 'admin', 'release_date', 'end_date')},
            },
        ),
    ]
