# Generated by Django 5.2.6 on 2025-11-14 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_hall_layout'),
        ('movies', '0002_delete_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieadmindetails',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='halls.hall'),
        ),
    ]
