# Generated by Django 5.2.6 on 2025-11-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movieadmindetails_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieadmindetails',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
