# Generated by Django 5.2.6 on 2025-11-27 21:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movieadmindetails_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieadmindetails',
            name='poster',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='poster'),
        ),
    ]
