# Generated by Django 5.2.6 on 2025-12-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_change_genre_to_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(blank=True, choices=[('PG', 'PG - Parental Guidance'), ('SPG', 'SPG - Strict Parental Guidance')], max_length=10),
        ),
    ]
