# Generated by Django 5.2.6 on 2025-12-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_rating_pg_spg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(blank=True, choices=[('G', 'G - General Audiences'), ('PG', 'PG - Parental Guidance'), ('SPG', 'SPG - Strict Parental Guidance')], max_length=10),
        ),
    ]
