# Generated by Django 5.2.6 on 2025-10-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_pendingadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingadmin',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='pendingadmin',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
