# Generated by Django 5.2.6 on 2025-10-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reel_time', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
