# Generated by Django 5.2.6 on 2025-11-14 08:03

import django.db.models.deletion
import reservations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_delete_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=255)),
                ('selected_date', models.DateField(default=reservations.models.get_tomorrow)),
                ('selected_showtime', models.CharField(max_length=50)),
                ('number_of_seats', models.PositiveIntegerField(default=1)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('movie_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='movies.movieadmindetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movies_reservation',
                'ordering': ['-reservation_date'],
            },
        ),
    ]
