# Generated by Django 5.2.6 on 2025-11-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='selected_seats',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
